name: Build Multiversion Multi-Platform Mod

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate version matrix
        id: set-matrix
        run: |
          versions=$(ls versionProperties/*.properties | xargs -n 1 basename | sed 's/.properties//' | jq -R -s -c 'split("\n")[:-1]')
          echo "versions=$versions" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-matrix.outputs.versions) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Make Gradle Wrapper and Build Script executable
        run: chmod +x gradlew; chmod +x buildall.sh

      - name: Build version ${{ matrix.version }}
        run: ./buildall.sh --version ${{ matrix.version }}

      - name: Upload artifact for ${{ matrix.version }}
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-${{ matrix.version }}
          path: allJars/*.jar
